apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-avxf
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0045-tenant/tkrw-pr712-0075-0045-app/devfile-sample-avxf@sha256:372e166597a01fab8fbfd24eeb757d50dd7c4ff16d3a1f904dabce0ed2aa4c9e
        name: my-nodejs
        resources: {}
status: {}
